In [17]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [18]:
X,y = load_iris(return_X_y=True)

In [19]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [20]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [21]:
X_test_scaled

array([[ 0.55185016, -1.29049444,  0.72381322,  0.94989649],
       [-0.28038347, -0.3782156 , -0.06940675,  0.15463431],
       [ 0.67074068,  0.30599353,  0.89378893,  1.48007127],
       [-1.1126171 ,  0.07792382, -1.25923669, -1.30334634],
       [ 0.7896312 ,  0.30599353,  0.78047179,  1.08244018],
       [-0.51816451,  0.76213295, -1.14591956, -1.30334634],
       [-0.75594555,  2.35862092, -1.25923669, -1.43589004],
       [ 1.74075535, -0.3782156 ,  1.46037461,  0.81735279],
       [-0.87483607, -1.29049444, -0.40935816, -0.11045308],
       [ 1.38408379,  0.30599353,  0.55383751,  0.28717801],
       [ 0.67074068,  0.07792382,  1.00710606,  0.81735279],
       [-1.23150762, -0.15014589, -1.31589526, -1.43589004],
       [-0.16149295,  1.67441179, -1.14591956, -1.17080265],
       [ 1.02741223,  0.07792382,  0.3838618 ,  0.28717801],
       [ 0.7896312 , -0.15014589,  1.00710606,  0.81735279],
       [-0.04260244, -0.83435502,  0.2138861 , -0.24299678],
       [ 0.07628808, -0.15014589,  0.27054467,  0.4197217 ],
       [-0.99372659, -2.43084299, -0.12606532, -0.24299678],
       [-1.35039814,  0.30599353, -1.20257813, -1.30334634],
       [ 1.02741223,  0.53406324,  1.1204232 ,  1.74515866],
       [ 1.62186483,  0.30599353,  1.29039891,  0.81735279],
       [-0.99372659,  0.99020266, -1.37255383, -1.17080265],
       [-0.04260244, -0.60628531,  0.78047179,  1.61261497],
       [-1.35039814,  0.30599353, -1.37255383, -1.30334634],
       [ 0.1951786 , -0.83435502,  0.78047179,  0.5522654 ],
       [-0.04260244, -0.83435502,  0.78047179,  0.94989649],
       [ 0.55185016, -0.3782156 ,  1.06376463,  0.81735279],
       [-0.87483607,  0.99020266, -1.31589526, -1.30334634],
       [ 1.02741223, -1.29049444,  1.17708177,  0.81735279],
       [-0.16149295, -1.29049444,  0.72381322,  1.08244018]])

In [22]:
from sklearn.datasets import fetch_openml
from sklearn.preprocessing import OrdinalEncoder

In [23]:
data = fetch_openml('car', as_frame = True).frame

/usr/local/lib/python3.12/dist-packages/sklearn/datasets/_openml.py:323: UserWarning: Multiple active versions of the dataset matching the name car exist. Versions may be fundamentally different, returning version 2. Available versions:
- version 2, status: active
  url: https://www.openml.org/search?type=data&id=991
- version 3, status: active
  url: https://www.openml.org/search?type=data&id=40975

  warn(warning_msg)

In [24]:
data

     buying  maint  doors persons lug_boot safety binaryClass
0     vhigh  vhigh      2       2    small    low           P
1     vhigh  vhigh      2       2    small    med           P
2     vhigh  vhigh      2       2    small   high           P
3     vhigh  vhigh      2       2      med    low           P
4     vhigh  vhigh      2       2      med    med           P
...     ...    ...    ...     ...      ...    ...         ...
1723    low    low  5more    more      med    med           N
1724    low    low  5more    more      med   high           N
1725    low    low  5more    more      big    low           P
1726    low    low  5more    more      big    med           N
1727    low    low  5more    more      big   high           N

[1728 rows x 7 columns]

In [25]:
columns_to_encode = ['lug_boot','safety']
encode = OrdinalEncoder(
  categories = [
      ['small','med','big'],
      ['low', 'med', 'high']
  ]
)
data[columns_to_encode] =  encode.fit_transform(data[columns_to_encode])

In [26]:
data = fetch_openml('adult', as_frame=True).frame

/usr/local/lib/python3.12/dist-packages/sklearn/datasets/_openml.py:323: UserWarning: Multiple active versions of the dataset matching the name adult exist. Versions may be fundamentally different, returning version 1. Available versions:
- version 1, status: active
  url: https://www.openml.org/search?type=data&id=179
- version 2, status: active
  url: https://www.openml.org/search?type=data&id=1590

  warn(warning_msg)

In [27]:
data

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capitalgain,capitalloss,hoursperweek,native-country,class
0,2,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,1,0,2,United-States,<=50K
1,3,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,0,United-States,<=50K
2,2,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,2,United-States,<=50K
3,3,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,2,United-States,<=50K
4,1,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,2,Cuba,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48837,2,Private,215419,Bachelors,13,Divorced,Prof-specialty,Not-in-family,White,Female,0,0,2,United-States,<=50K
48838,4,NaN,321403,HS-grad,9,Widowed,NaN,Other-relative,Black,Male,0,0,2,United-States,<=50K
48839,2,Private,374983,Bachelors,13,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,3,United-States,<=50K
48840,2,Private,83891,Bachelors,13,Divorced,Adm-clerical,Own-child,Asian-Pac-Islander,Male,2,0,2,United-States,<=50K
48841,1,Self-emp-inc,182148,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,3,United-States,>50K

In [28]:
from sklearn.preprocessing import OneHotEncoder

In [29]:
data.occupation.value_counts()

occupation
Prof-specialty       6172
Craft-repair         6112
Exec-managerial      6086
Adm-clerical         5611
Sales                5504
Other-service        4923
Machine-op-inspct    3022
Transport-moving     2355
Handlers-cleaners    2072
Farming-fishing      1490
Tech-support         1446
Protective-serv       983
Priv-house-serv       242
Armed-Forces           15
Name: count, dtype: int64

In [30]:
import pandas as pd
encoder = OneHotEncoder(handle_unknown = 'ignore', sparse_output = False)
encoded_values = encoder.fit_transform(data [['occupation','race']])
new_cols = encoder.get_feature_names_out(['occupation','race'])

In [31]:
df_encoded = pd.DataFrame(encoded_values, columns = new_cols, index = data.index)
data_final = pd.concat(
    [data.drop(columns = ['occupation','race']), df_encoded],
    axis = 1
)

In [32]:
data_final

,age,workclass,fnlwgt,education,education-num,marital-status,relationship,sex,capitalgain,capitalloss,...,occupation_Protective-serv,occupation_Sales,occupation_Tech-support,occupation_Transport-moving,occupation_nan,race_Amer-Indian-Eskimo,race_Asian-Pac-Islander,race_Black,race_Other,race_White
0,2,State-gov,77516,Bachelors,13,Never-married,Not-in-family,Male,1,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1,3,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Husband,Male,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2,2,Private,215646,HS-grad,9,Divorced,Not-in-family,Male,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
3,3,Private,234721,11th,7,Married-civ-spouse,Husband,Male,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
4,1,Private,338409,Bachelors,13,Married-civ-spouse,Wife,Female,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48837,2,Private,215419,Bachelors,13,Divorced,Not-in-family,Female,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
48838,4,NaN,321403,HS-grad,9,Widowed,Other-relative,Male,0,0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
48839,2,Private,374983,Bachelors,13,Married-civ-spouse,Husband,Male,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
48840,2,Private,83891,Bachelors,13,Divorced,Own-child,Male,2,0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
48841,1,Self-emp-inc,182148,Bachelors,13,Married-civ-spouse,Husband,Male,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0